In [2]:
import csv
import numpy as np 
import pandas as pd
import pickle

pd.set_option('display.max_rows', 4000)
pd.set_option('display.max_columns', 200)

**Baseline User DataFrames**

In [6]:
BaselineDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/RB_timelineDF_090320.pkl")

In [7]:
BaselineDF.head(5)

,username,tweet_count,sentiment_scores,trump_count,clinton_count,trump_sent,clinton_sent,positive_sent,negative_sent
0,desrosierseryka,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,financial_guru,"[0, 0, 0, 0, 0, 21, 3, 3, 0, 3, 0, 0, 3, 2, 0,...","[[], [], [], [], [], [0.4019, 0.7096, 0.34, 0....","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [0.4019, 0.7096, 0.34, 0....","[[], [], [], [], [], [-0.3802, -0.1531, -0.400..."
2,sarahcascarino,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,crapulon,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [0.25...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [0.25...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,skipfidura,"[18, 30, 24, 39, 8, 12, 12, 14, 24, 12, 14, 1,...","[[0.0, 0.4404, -0.296, 0.0, 0.0, 0.4019, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[0.4404, 0.4019, 0.4859, 0.3182, 0.5106], [0....","[[-0.296, -0.4588], [-0.4341, -0.2023, -0.6131..."

**This DataFrame is all of the baseline users with all of their characteristics. There are also these more specific DataFrames for each different metric, which I use to plot:**

In [8]:
BL_tweet_countDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/RB_tweet_countDF_090320.pkl")
BL_trump_countDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/RB_trump_countDF_090320.pkl")
BL_clinton_countDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/RB_clinton_countDF_090320.pkl")
BL_sentiment_scoresDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/RB_sentiment_scoresDF_090320.pkl")
BL_trump_sentDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/RB_trump_sentDF_090320.pkl")
BL_clinton_sentDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/RB_clinton_sentDF_090320.pkl")
BL_positive_sentDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/RB_positive_sentDF_090320.pkl")
BL_negative_sentDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/RB_negative_sentDF_090320.pkl")

**For these DataFrames, each row represents a single user's history. Entries are either sums or averages depending on the metric (e.g., tweet counts are monthly sums, but senimtent scores are monthly means.**

In [9]:
BL_tweet_countDF.head()

,01-2009,02-2009,03-2009,04-2009,05-2009,06-2009,07-2009,08-2009,09-2009,10-2009,11-2009,12-2009,01-2010,02-2010,03-2010,04-2010,05-2010,06-2010,07-2010,08-2010,09-2010,10-2010,11-2010,12-2010,01-2011,02-2011,03-2011,04-2011,05-2011,06-2011,07-2011,08-2011,09-2011,10-2011,11-2011,12-2011,01-2012,02-2012,03-2012,04-2012,05-2012,06-2012,07-2012,08-2012,09-2012,10-2012,11-2012,12-2012,01-2013,02-2013,03-2013,04-2013,05-2013,06-2013,07-2013,08-2013,09-2013,10-2013,11-2013,12-2013,01-2014,02-2014,03-2014,04-2014,05-2014,06-2014,07-2014,08-2014,09-2014,10-2014,11-2014,12-2014,01-2015,02-2015,03-2015,04-2015,05-2015,06-2015,07-2015,08-2015,09-2015,10-2015,11-2015,12-2015,01-2016,02-2016,03-2016,04-2016,05-2016,06-2016,07-2016,08-2016,09-2016,10-2016,11-2016,12-2016
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,106.0,404.0,80.0,142.0,86.0,129.0,45.0,0.0,2.0,26.0,0.0,1.0,1.0,5.0,10.0,16.0,12.0,1.0,1.0,0.0,1.0,9.0,6.0,1.0,3.0,9.0,8.0,1.0,1.0,13
1,NaN,NaN,NaN,NaN,NaN,21.0,3.0,3.0,0.0,3.0,0.0,0.0,3.0,2.0,0.0,4.0,1.0,4.0,0.0,1.0,0.0,5.0,5.0,1.0,2.0,1.0,8.0,2.0,7.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,32.0,11.0,0.0,1.0,2.0,0.0,1.0,15.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,25.0,20.0,13.0,3.0,3.0,1.0,4.0,2.0,4.0,0.0,0.0,3.0,1.0,1.0,0.0,0.0,1.0,3.0,0.0,1.0,5.0,0.0,0.0,2.0,0.0,3.0,1.0,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,6.0,30.0,11.0,100.0,225.0,130.0,156.0,350.0,427.0,363.0,468.0,710.0,358.0,311.0,257.0,310.0,309.0,271.0,249.0,253.0,255.0,280.0,405.0,391.0,221.0,160.0,133.0,413.0,525.0,83.0,381.0,732.0,683.0,55.0,283.0,294.0,139.0,272.0,214.0,231.0,197.0,179.0,138.0,0.0,0.0,85.0,202.0,241.0,140
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,2.0,1.0,3.0,1.0,1.0,11.0,0.0,0.0,2.0,0.0,0.0,0.0,3.0,1.0,10.0,2.0,5.0,5.0,9.0,7.0,2.0,4.0,21.0,10.0,46.0,22.0,22.0,23.0,11.0,16.0,8.0,9.0,7.0,2.0,18.0,28.0,23.0,15.0,14.0,7.0,5.0,6.0,12.0,15.0,46.0,7.0,0.0,0.0,8.0,12.0,23.0,31.0,31.0,22.0,28.0,14
4,18.0,30.0,24.0,39.0,8.0,12.0,12.0,14.0,24.0,12.0,14.0,1.0,12.0,9.0,10.0,3.0,2.0,6.0,3.0,10.0,11.0,10.0,16.0,9.0,11.0,46.0,11.0,4.0,0.0,30.0,22.0,13.0,15.0,27.0,4.0,17.0,1.0,3.0,0.0,3.0,65.0,18.0,17.0,20.0,5.0,11.0,23.0,5.0,43.0,25.0,43.0,8.0,9.0,35.0,61.0,34.0,51.0,31.0,72.0,49.0,86.0,65.0,108.0,49.0,45.0,51.0,79.0,38.0,56.0,35.0,48.0,16.0,19.0,32.0,83.0,60.0,37.0,16.0,43.0,36.0,26.0,44.0,40.0,34.0,51.0,58.0,52.0,36.0,47.0,25.0,58.0,8.0,68.0,36.0,33.0,21

In [10]:
BL_negative_sentDF.head()

,01-2009,02-2009,03-2009,04-2009,05-2009,06-2009,07-2009,08-2009,09-2009,10-2009,11-2009,12-2009,01-2010,02-2010,03-2010,04-2010,05-2010,06-2010,07-2010,08-2010,09-2010,10-2010,11-2010,12-2010,01-2011,02-2011,03-2011,04-2011,05-2011,06-2011,07-2011,08-2011,09-2011,10-2011,11-2011,12-2011,01-2012,02-2012,03-2012,04-2012,05-2012,06-2012,07-2012,08-2012,09-2012,10-2012,11-2012,12-2012,01-2013,02-2013,03-2013,04-2013,05-2013,06-2013,07-2013,08-2013,09-2013,10-2013,11-2013,12-2013,01-2014,02-2014,03-2014,04-2014,05-2014,06-2014,07-2014,08-2014,09-2014,10-2014,11-2014,12-2014,01-2015,02-2015,03-2015,04-2015,05-2015,06-2015,07-2015,08-2015,09-2015,10-2015,11-2015,12-2015,01-2016,02-2016,03-2016,04-2016,05-2016,06-2016,07-2016,08-2016,09-2016,10-2016,11-2016,12-2016
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.525500,NaN,NaN,-0.339800,NaN,NaN,NaN,NaN,NaN,NaN,-0.575200,-0.395858,-0.388627,-0.338619,-0.448170,-0.512643,-0.363367,NaN,NaN,-0.326450,NaN,NaN,NaN,NaN,-0.200300,NaN,-0.48155,NaN,NaN,NaN,NaN,NaN,-0.555000,NaN,-0.151100,NaN,-0.569600,NaN,NaN,-0.192700
1,NaN,NaN,NaN,NaN,NaN,-0.3356,NaN,-0.71840,NaN,-0.1280,NaN,NaN,NaN,NaN,NaN,-0.4329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.4767,-0.3239,NaN,-0.22630,NaN,-0.8016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5574,-0.472675,NaN,-0.40190,-0.31820,NaN,NaN,-0.429550,NaN,NaN,NaN,NaN,-0.419900,NaN,NaN,NaN,NaN,NaN,-0.509300,NaN,NaN,NaN,-0.353767,-0.550433,-0.457067,NaN,-0.214800,NaN,NaN,-0.175900,-0.441150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.6118,-0.860233,-0.383991,-0.73140,-0.54405,-0.436636,-0.480054,-0.538434,-0.394675,-0.423777,-0.426877,-0.407827,-0.394840,-0.424731,-0.423342,-0.367856,-0.418874,-0.450038,-0.405352,-0.420162,-0.423931,-0.456275,-0.420707,-0.416667,-0.416043,-0.438816,-0.418068,-0.354095,-0.436006,-0.436210,-0.480787,-0.392036,-0.465067,-0.468980,-0.311188,-0.438363,-0.45438,-0.507719,-0.443944,-0.436018,-0.388727,-0.422761,-0.421165,-0.457309,NaN,NaN,-0.382809,-0.462777,-0.43870,-0.449219
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.296,NaN,NaN,NaN,-0.30235,NaN,NaN,-0.32775,NaN,NaN,-0.381800,NaN,NaN,NaN,NaN,NaN,-0.468740,NaN,-0.385900,-0.401900,-0.450933,-0.762850,-0.340000,-0.386350,-0.413667,-0.446525,-0.442356,-0.404960,-0.494660,-0.415120,-0.296000,-0.509537,-0.591400,-0.424650,-0.450950,-0.051600,-0.328025,-0.364760,-0.528917,-0.337550,-0.265933,-0.526700,-0.483250,-0.153100,-0.18195,-0.362900,-0.404725,NaN,NaN,NaN,-0.401900,-0.296000,-0.491975,-0.3271,-0.512437,-0.514517,-0.45265,-0.604733
4,-0.3774,-0.42074,-0.545,-0.435571,-0.41895,-0.2855,-0.4588,-0.47755,-0.548083,-0.4653,-0.5423,NaN,-0.5423,-0.2003,-0.360275,-0.4767,NaN,-0.55875,-0.5574,NaN,-0.54155,-0.3612,-0.4424,-0.3182,-0.3939,-0.337967,-0.45595,-0.0772,NaN,-0.520167,-0.267325,-0.5423,-0.5574,-0.40728,NaN,-0.34,NaN,NaN,NaN,NaN,-0.38595,-0.32125,NaN,-0.501929,NaN,NaN,-0.2846,-0.226300,-0.253400,-0.17365,-0.39870,-0.515550,-0.571900,-0.372500,-0.301473,-0.426200,-0.347750,-0.491100,-0.460533,-0.322186,-0.513800,-0.462371,-0.431955,-0.415920,-0.413211,-0.180250,-0.400010,-0.510675,-0.448160,NaN,-0.329300,-0.250000,-0.128000,-0.314675,-0.406536,-0.351757,-0.444933,-0.296000,-0.195800,-0.251917,NaN,-0.462050,-0.10270,-0.363467,-0.295400,-0.336410,-0.462989,-0.429600,-0.375700,-0.473633,-0.256100,NaN,-0.289314,-0.653943,-0.50450,NaN

**NaN entries are not values and are not considered when working with column operations, such as sums or averages. NaN values are ignored in these cases. NaN values are used because users had not yet shown account activity for the first time. After activity is detected nonactive months will be reflected as 0s and not NaNs.**

**Now, we can do the same for the targetted Twitter users:**

In [11]:
TargetedUsersDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/PAU_timelineDF_090320.pkl")

In [12]:
TargetedUsersDF.head()

,username,tweet_count,sentiment_scores,trump_count,clinton_count,trump_sent,clinton_sent,positive_sent,negative_sent
0,rustyrockets,"[17, 28, 289, 207, 191, 65, 95, 43, 35, 28, 38...","[[0.8402, -0.1531, -0.4767, 0.0, -0.296, -0.67...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[0.8402, 0.0516, 0.4195, 0.6705, 0.0772, 0.51...","[[-0.1531, -0.4767, -0.296, -0.6705, -0.4005],..."
1,mtaibbi,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,reba,"[0, 0, 0, 2, 64, 54, 50, 79, 102, 34, 40, 4, 2...","[[], [], [], [0.0, 0.0], [0.6588, 0.7243, -0.3...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [0.6588, 0.7243, 0.5538, 0.76...","[[], [], [], [], [-0.34, -0.296, -0.5466, -0.5..."
3,marclamonthill,"[0, 6, 84, 161, 386, 453, 559, 582, 856, 766, ...","[[], [-0.5719, 0.0, 0.0, -0.4767, 0.0, 0.5994]...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [0.5994], [0.5859, 0.5859, 0.4404, 0.7506...","[[], [-0.5719, -0.4767], [-0.4389, -0.8591, -0..."
4,Liz_Wheeler,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [13]:
TU_tweet_countDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/PAU_tweet_countDF_090320.pkl")
TU_trump_countDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/PAU_trump_countDF_090320.pkl")
TU_clinton_countDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/PAU_clinton_countDF_090320.pkl")
TU_sentiment_scoresDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/PAU_sentiment_scoresDF_090320.pkl")
TU_trump_sentDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/PAU_trump_sentDF_090320.pkl")
TU_clinton_sentDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/PAU_clinton_sentDF_090320.pkl")
TU_positive_sentDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/PAU_positive_sentDF_090320.pkl")
TU_negative_sentDF = pd.read_pickle("/home/rhetthanscom/TimelineAnalysis/PAU_negative_sentDF_090320.pkl")

In [14]:
TU_negative_sentDF.head()

,01-2009,02-2009,03-2009,04-2009,05-2009,06-2009,07-2009,08-2009,09-2009,10-2009,11-2009,12-2009,01-2010,02-2010,03-2010,04-2010,05-2010,06-2010,07-2010,08-2010,09-2010,10-2010,11-2010,12-2010,01-2011,02-2011,03-2011,04-2011,05-2011,06-2011,07-2011,08-2011,09-2011,10-2011,11-2011,12-2011,01-2012,02-2012,03-2012,04-2012,05-2012,06-2012,07-2012,08-2012,09-2012,10-2012,11-2012,12-2012,01-2013,02-2013,03-2013,04-2013,05-2013,06-2013,07-2013,08-2013,09-2013,10-2013,11-2013,12-2013,01-2014,02-2014,03-2014,04-2014,05-2014,06-2014,07-2014,08-2014,09-2014,10-2014,11-2014,12-2014,01-2015,02-2015,03-2015,04-2015,05-2015,06-2015,07-2015,08-2015,09-2015,10-2015,11-2015,12-2015,01-2016,02-2016,03-2016,04-2016,05-2016,06-2016,07-2016,08-2016,09-2016,10-2016,11-2016,12-2016
0,-0.39936,-0.334638,-0.434502,-0.377245,-0.391806,-0.416718,-0.317800,-0.521200,-0.465778,-0.413189,-0.394800,-0.402108,-0.582933,-0.441625,-0.411050,-0.410710,-0.475000,-0.413960,-0.415000,-0.457245,-0.403764,-0.320100,-0.444660,-0.546987,-0.45050,-0.304783,-0.506390,-0.417394,-0.326190,-0.226050,-0.431125,-0.456957,-0.459700,-0.474620,-0.419775,-0.498900,NaN,NaN,-0.548125,-0.771700,-0.420419,-0.467767,-0.403957,-0.517218,NaN,-0.665033,-0.439858,-0.420727,-0.459625,-0.438350,-0.412842,-0.438392,-0.449618,-0.414909,-0.479764,-0.403162,-0.455414,-0.410187,-0.442965,-0.509687,-0.411556,-0.424920,-0.463189,-0.420146,-0.491868,-0.443030,-0.353383,-0.345806,-0.519189,-0.390532,-0.425293,-0.472597,-0.367500,-0.469383,-0.477856,-0.485800,-0.476583,-0.334550,-0.560808,-0.266650,NaN,-0.153100,-0.476700,NaN,NaN,NaN,NaN,NaN,-0.497300,-0.338900,-0.905900,NaN,-0.440400,-0.431475,-0.494787,-0.382329
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.518125,-0.202300,-0.332400,-0.605450,-0.578900,-0.585900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.310400,-0.427550,NaN,-0.440400,NaN,NaN,-0.604375,-0.467162,-0.360318,-0.518372,-0.382920,-0.453069,-0.541250,-0.410527,-0.519857,-0.561050,-0.444700,-0.400086,-0.388831,-0.432833,-0.447571,-0.421619,-0.351871,-0.459770,-0.504367,-0.357367,-0.440829,-0.522512,-0.394654,-0.584400,-0.545910,-0.346331,-0.383933,-0.449578,-0.482867,-0.432433,-0.260400,-0.433767,-0.438401,-0.466851,-0.468504,-0.466507,-0.455921,-0.490402,-0.464694,-0.451121,-0.418758,-0.438902,-0.405554,-0.435343,-0.418705,-0.425955,-0.378048,-0.454507,-0.435263,-0.380007,-0.453300,-0.440210,-0.367225,-0.402625,-0.431248,-0.432207,-0.413579
2,NaN,NaN,NaN,NaN,-0.348767,-0.656600,NaN,-0.437517,-0.504233,-0.252250,-0.513150,NaN,NaN,NaN,-0.552600,NaN,-0.182575,NaN,-0.431696,-0.354167,-0.247167,-0.488471,-0.344388,-0.336200,-0.28998,-0.439100,-0.153100,-0.274375,-0.372025,-0.328440,-0.564475,-0.357889,-0.333712,-0.479680,-0.380800,NaN,-0.455050,-0.402167,-0.296000,-0.379800,-0.315077,-0.290789,-0.306720,-0.383920,-0.453660,-0.392725,-0.391350,-0.224550,-0.219233,-0.557288,-0.326120,-0.416785,-0.487660,NaN,-0.354400,-0.282433,-0.241600,-0.534100,-0.323125,-0.282140,-0.554950,-0.507100,-0.520300,-0.408033,-0.409820,NaN,-0.620900,NaN,NaN,-0.521600,-0.340000,-0.153100,-0.400073,-0.487500,-0.280225,-0.343283,-0.364700,-0.484700,NaN,-0.409800,-0.259300,-0.311700,-0.365300,-0.319833,-0.298200,-0.336375,-0.402100,-0.264400,NaN,NaN,-0.314950,NaN,-0.445950,-0.310800,-0.224400,-0.476700
3,NaN,-0.524300,-0.463887,-0.435191,-0.471742,-0.449189,-0.438669,-0.419075,-0.424855,-0.445462,-0.445836,-0.462006,-0.448023,-0.430968,-0.451501,-0.369636,-0.481843,-0.465563,-0.457948,-0.511426,-0.471943,-0.461540,-0.481851,-0.499394,NaN,NaN,NaN,NaN,-0.406429,-0.467369,-0.469412,-0.406531,-0.458057,-0.497156,-0.466750,-0.477634,-0.460367,-0.430376,-0.477779,-0.431749,-0.405093,-0.447221,NaN,-0.520009,-0.398498,-0.438233,-0.484934,-0.411577,-0.451894,-0.451156,-0.520117,-0.465142,-0.489066,-0.424355,-0.459799,-0.486542,-0.441923,-0.467723,-0.447104,-0.438423,-0.444630,-0.429236,-0.462555,-0.502582,-0.451722,-0.474898,-0.466046,-0.479162,-0.447838,-0.498497,-0.480909,-0.460403,-0.494932,-0.495663,-0.465518,-0.464680,-0.478215,-0.467847,-0.466816,-0.405494,-0.446980,-0.459386,-0.441398,-0.429972,-0.443623,-0.438383,-0.448840,-0.468656,-0.478007,-0.446198,-0.432452,-0.430561,-0.460609,-0.461667,-0.424863,-0.435219
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.408653,-0.416717,-0.418819,-0.375642,-0.375041,-0.413390,-0.402831,-0.428772,-0.448125,-0.426529,-0.464702,-0.405913,-0.386491,-0.380242,-0.432348,-0.438012,-0.434302,-0.441302,-0.386687,-0.420073,-0.396408,-0.480220,-0.486654,-0.457379,-0.447363,-0.518448,-0.487199,-0.485768,-0.520259,-0.449793,-0.445927,-0.397033,-0.379080,-0.500404,-0.417567,-0.480768,-0.421223,-0.416619,-0.364120,-0.413855,-0.432483,-0.542300,NaN,NaN,-0.380314,-0.378550,-0.292450,-0.393350,NaN,-0.308936,-0.418873,-0.514860,-0.413443,-0.401125,-0.276700,-0.466450,-0.523150,-0.552280,-0.500796,-0.439131,-0.527366,-0.496982,-0.504439,-0.647313,-0.468714,-0.488345,-0.495615,-0.473312,-0.529101,-0.512414